### ISSUE TITLE
Controller is connected manually, Unity scene says it's not

### ISSUE THREAD

**Issue by frnzmlc** [FinchTechnologies/FinchUnitySDK#1]
macOS Sierra

<img width="904" alt="screen shot 2018-12-13 at 19 28 17" src="https://user-images.githubusercontent.com/32875334/49959356-a1dbe280-ff0d-11e8-9dcc-3564d352d288.png">

**Comment by Neargye** [comment]
What version of sdk are you using?

**Comment by frnzmlc** [comment]
@Neargye still doesn't connect

**Comment by Neargye** [comment]
@LiterusNexus Please check this issues.

**Comment by frnzmlc** [comment]
@LiterusNexus The hardware info is attached, nRF can't connect to any Bluetooth devices, so I can't provide firmware info.

[output.txt](https://github.com/FinchTechnologies/FinchUnitySDK/files/2691654/output.txt)
