### ISSUE TITLE
Controller goes to sleep while in use

### ISSUE THREAD

**Issue by frnzmlc** [FinchTechnologies/FinchUnitySDK#2]
Windows 10 problem.

If I don't press a button every once in a while, the controller goes to sleep mode. There should be an option to keep sending data despite this - for cases when the user wants to use only the IMU.

**Comment by Neargye** [comment]
The controllers will not go to sleep mode if the run application that uses FinchSDK and device connected.

**Comment by frnzmlc** [comment]
@Neargye Should I send a video of the behavior?

**Comment by Neargye** [comment]
@frnzmlc yes, you can send here or on dg@finch-vr.com
